export const env = {
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3000',
  natioPublicResource: import.meta.env.VITE_NATIO_PUBLIC_RESOURCE ?? '/api/natio',
  natioAdminResource: import.meta.env.VITE_NATIO_ADMIN_RESOURCE ?? '/api/admin/natio',
  villePublicResource: import.meta.env.VITE_VILLE_PUBLIC_RESOURCE ?? '/api/ville',
  villeAdminResource: import.meta.env.VITE_VILLE_ADMIN_RESOURCE ?? '/api/admin/ville',
  arbitrePublicResource: import.meta.env.VITE_ARBITRE_PUBLIC_RESOURCE ?? '/api/arbitre',
  arbitreAdminResource: import.meta.env.VITE_ARBITRE_ADMIN_RESOURCE ?? '/api/admin/arbitre',
  joueurPublicResource: import.meta.env.VITE_JOUEUR_PUBLIC_RESOURCE ?? '/api/joueurs',
  joueurAdminResource: import.meta.env.VITE_JOUEUR_ADMIN_RESOURCE ?? '/api/admin/joueurs',
  terrainPublicResource: import.meta.env.VITE_TERRAIN_PUBLIC_RESOURCE ?? '/api/terrains',
  terrainAdminResource: import.meta.env.VITE_TERRAIN_ADMIN_RESOURCE ?? '/api/admin/terrains',
  devisePublicResource: import.meta.env.VITE_DEVISE_PUBLIC_RESOURCE ?? '/api/devises',
  deviseAdminResource: import.meta.env.VITE_DEVISE_ADMIN_RESOURCE ?? '/api/admin/devises',
  circPublicResource: import.meta.env.VITE_CIRC_PUBLIC_RESOURCE ?? '/api/circs',
  circAdminResource: import.meta.env.VITE_CIRC_ADMIN_RESOURCE ?? '/api/admin/circs',
  epreuvePublicResource: import.meta.env.VITE_EPREUVE_PUBLIC_RESOURCE ?? '/api/epreuves',
  epreuveAdminResource: import.meta.env.VITE_EPREUVE_ADMIN_RESOURCE ?? '/api/admin/epreuves',
};
